---

- name: weave-scope | Getting weave-scope installation files
  copy:
    src: "{{ item }}"
    dest: "{{ kubesphere_dir }}/"
  loop:
    - weave-scope

# Roshan:Debug
- name: Roshan:Debug weave-scope | Getting weave-scope installation files
  debug:
    msg: copy weave-scope files from weave-scope to {{ kubesphere_dir }}/

- name: weave-scope | Creating manifests
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ kubesphere_dir }}/weave-scope/{{ item.file }}"
  with_items:
    - { type: ds, file: weave-scope.yaml }

# Roshan:Debug
- name: Roshan:Debug weave-scope | Creating manifests
  debug:
    msg: template weave-scope files from weave-scope weave-scope.yaml.j2 to {{ kubesphere_dir }}/weave-scope yaml files

- name: weave-scope | Deploying weave-scope
  shell: >
    {{ bin_dir }}/kubectl apply -f {{ kubesphere_dir }}/weave-scope/weave-scope.yaml
  register: weave_result
  failed_when: "weave_result.stderr and 'Warning' not in weave_result.stderr and 'spec.clusterIP' not in weave_result.stderr"
  until: weave_result is succeeded
  retries: 5
  delay: 3

# Roshan:Debug
- name: Roshan:Debug weave-scope | Deploying weave-scope
  debug:
    msg: execute 'kubectl apply -f {{ kubesphere_dir }}/weave-scope/weave-scope.yaml' and register the output to weave_result, result is {{ weave_result.stdout }}

- name: weave-scope | Importing weave-scope status
  shell: >
    {{ bin_dir }}/kubectl patch cc ks-installer
    --type merge
    -p '{"status": {"network": {"topology": {"status": "enabled", "enabledTime": "{{ lookup('pipe','date  +%Y-%m-%dT%H:%M:%S%Z') }}"}}}}'
    -n kubesphere-system
  register: cc_result
  failed_when: "cc_result.stderr and 'Warning' not in cc_result.stderr"
  until: cc_result is succeeded
  retries: 5
  delay: 3

# Roshan:Debug
- name: Roshan:Debug weave-scope | Importing weave-scope status
  debug:
    msg: execute "kubectl patch cc ks-installer" and cc_result is succeeded